exercism/elm-analyzer

- elm.json
- review/elm.json
- src/Exercise/BettysBikeShop.elm
- src/ReviewConfig.elm
- tests/Exercise/BettysBikeShopTest.elm
Closes #17.
[Sister PR here](https://github.com/exercism/website-copy/pull/2186).
The `design.md` document mentions two things:
-   Verify that functions have type annotations.
-  Verify that the whitespace adheres to community defaults.
This PR covers the first one, but I don't know how to address the second one (which is also mentioned for a couple of other concept exercises). 
Formatting in Elm is so reliant on `elm-format` that I don't think it makes sense to ask students to emulate that. [There is an open issue](https://github.com/exercism/exercism/issues/5986) that talks about adding a format button on the web editor. I'm not sure how far that had gone, but if we could have an `elm-format` button, that would solve everything.
> Add analyzer rule for `bettys-bike-shop`

- Dockerfile
The analyzer is down at the moment because `lts-alpine` is not happy with the specific version of curl.
This should fix it.
EDIT: it's not actually down, sorry. The new check didn't get released, that's all.
> Remove curl specific version

- src/Exercise/TopScorers.elm
- src/ReviewConfig.elm
- tests/Exercise/TopScorersTest.elm
Add analyser rules for the Top Scorers concept exercise
[Sister PR in webste-copy](https://github.com/exercism/website-copy/pull/2224)
Covers the following points from [design.md](https://github.com/exercism/elm/blob/main/exercises/concept/top-scorers/.meta/design.md)
- filter must be used in removeInsignificantPlayers
- insert must be used in resetPlayerCounts
- sort must not be used in formatPlayers
- updateGoalCountForPlayer and List.foldl must be used in aggregateScorers
- Maybe.map and Maybe.withDefault should be used in formatPlayer
- merge must be used in combineGames
@jiegillet 
@mpizenberg
> Top scorers

- .github/workflows/elm_tests.yml
- src/Analyzer.elm
- src/Exercise/BlorkemonCards.elm
- src/ReviewConfig.elm
- tests/AnalyzerTest.elm
- tests/Exercise/BlorkemonCardsTest.elm
Closes #42.
I didn't follow exactly the design document, I added one to check that `maxPower` uses `max` (to my surprise, someone didn't) and I removed `sortByCoolness` uses `List.sortBy` because the hints also present `List.sortWith` as a possibility.
~~I'm too sleepy for doing the comment PR, so that will have to wait for tomorrow, I think.~~
[Sister PR here](https://github.com/exercism/website-copy/pull/2229).
The CI broke because the brand new version of elm-test requires `elm-explorations/test` 2.0, so I fixed it for now, I will do a dependency update later.
> Write analysis for concept exercise `blorkemon-cards`

- .github/workflows/elm_tests.yml
- README.md
- bin/check_website-copy_paths.sh
- src/Analyzer.elm
- src/Comment.elm
- src/Common/NoUnused.elm
- src/Common/Simplify.elm
- src/Exercise/BettysBikeShop.elm
- src/Exercise/BlorkemonCards.elm
- src/Exercise/MariosMarvellousLasagna.elm
- src/Exercise/Strain.elm
- src/Exercise/TopScorers.elm
- src/Exercise/TwoFer.elm
- src/Main.elm
- src/RuleConfig.elm
- tests/AnalyzerTest.elm
- tests/CommentTest.elm
- tests/Common/NoUnusedTest.elm
- tests/Common/SimplifyTest.elm
- tests/Exercise/BettysBikeShopTest.elm
- tests/Exercise/BlorkemonCardsTest.elm
- tests/Exercise/MariosMarvellousLasagnaTest.elm
- tests/Exercise/StrainTest.elm
- tests/Exercise/TopScorersTest.elm
- tests/Exercise/TwoFerTest.elm
We have been burned before by typos in the comment paths (`elm.blorkemon-cards.use_sort_by`), because they have to match an equivalent file in `website-copy` (`analyzer-comments/elm/blorkemon-cards/use_sort_by.md`).
This PR adds a CI check to make sure that all paths exist.
Of course, that means that all new PRs with new comments will fail until the comments are merged in `website-copy`.
I was only able to do that after a major refactor best explained by this diff
```diff
type AnalyzerRule
-    = CustomRule Rule
-    | ImportedRule Rule (Decoder Comment)
+    = CustomRule (Comment -> Rule) Comment
+    | ImportedRule Rule (Comment -> Decoder Comment) Comment
```
`Review.Rule` is an opaque type, so it is impossible to extract comments from it, so I had to separate the comments on the top …
> Add CI check: all comment paths exist in `website-copy`

- src/Analyzer.elm
- src/Exercise/TracksOnTracksOnTracks.elm
- src/ReviewConfig.elm
- tests/AnalyzerTest.elm
- tests/Exercise/BlorkemonCardsTest.elm
- tests/Exercise/TracksOnTracksOnTracksTest.elm
Closes #23
[Sister PR here](https://github.com/exercism/website-copy/pull/2236).
@ceddlyburge this also introduces a new `Operator` variant we can use for the composition concept.
> Add analysis for `tracks-on-tracks-on-tracks`

- src/Exercise/CustomSet.elm
- src/ReviewConfig.elm
- tests/Exercise/CustomSetTest.elm
Closes #49.
[Sister PR here](https://github.com/exercism/website-copy/pull/2284).
Pretty straightforward one using `Analyzer.functionCalls` :)
> Add rule for practice exercise `custom-set`

- src/Exercise/TopScorers.elm
- tests/Exercise/TopScorersTest.elm
Closes #56 
I didn't change the analyzer comment
> `aggregateScorers` is most easily written using `List.foldl` and `updateGoalCountForPlayer`.
because it's still true, but should I? If someone uses `List.foldr` but not `updateGoalCountForPlayer`, would they be confused and change both? It's not a huge deal I guess.
> Allow the use of `List.foldr` in `top-scorers`

- src/Exercise/ValentinesDay.elm
- src/ReviewConfig.elm
- tests/Exercise/ValentinesDayTest.elm
Closes #18 
[Sister PR here](https://github.com/exercism/website-copy/pull/2286).
I picked this one because I thought that the analyzer couldn't detect `case` statements but... It can already :p
> Add rule for concept exercise `valentines-day`

- src/ElmSyntaxHelpers.elm
- src/Exercise/TreasureFactory.elm
- src/ReviewConfig.elm
- tests/ElmSyntaxHelpersTest.elm
- tests/Exercise/BettysBikeShopTest.elm
- tests/Exercise/TreasureFactoryTest.elm
Closes #57
[Sister PR here](https://github.com/exercism/website-copy/pull/2285).
The way to specify signatures is super verbose, but I think it's still the best way to do it.
> Add rules for concept exercise `treasure-factory`

- elm.json
- review/elm.json
- review/src/ReviewConfig.elm
- src/Common/NoDebug.elm
- src/ReviewConfig.elm
- tests/Common/NoDebugTest.elm
- tests/Common/NoUnusedTest.elm
- tests/Common/SimplifyTest.elm
[Sister PR here](https://github.com/exercism/website-copy/pull/2291).
Part of #13.
This check is meant to be a rule checked against all solutions, and warns students against publishing solution with `Debug` functions in them.
There are two more common rules that I feel are appropriate after this one:
- Disallow `-- TODO` comments (some stubs have this, sometimes students don't remove them, but it's just noise)
- Comment on variable names not in camelCase, since it's such a strong standard in Elm
Anything else from the list on the issue is not as clear to me and would need discussion.
> Add common rule for all exercises: no `Debug` functions

- src/Analyzer.elm
- src/ElmSyntaxHelpers.elm
- src/Exercise/Bandwagoner.elm
- src/Exercise/BlorkemonCards.elm
- src/Exercise/CustomSet.elm
- src/Exercise/ListOps.elm
- src/Exercise/MariosMarvellousLasagna.elm
- src/Exercise/MazeMaker.elm
- src/Exercise/Strain.elm
- src/Exercise/TicketPlease.elm
- src/Exercise/TopScorers.elm
- src/Exercise/TracksOnTracksOnTracks.elm
- src/Exercise/TwoFer.elm
- src/Exercise/ValentinesDay.elm
- src/ReviewConfig.elm
- tests/AnalyzerTest.elm
- tests/ElmSyntaxHelpersTest.elm
- tests/Exercise/TicketPleaseTest.elm
Closes #26 
[Sister PR here](https://github.com/exercism/elm-analyzer/pull/69#issue-1979211705).
This one was a complex one, because I had to detect pattern matching in a wide variety of settings (function arguments, case statements, let blocks, lamdba functions). Not all patterns are detected (just what was needed) but adding more would be trivial.
I also did some refactors, mostly renaming functions.
> Add rules for concept exercise `ticket-please`

- .github/workflows/elm_tests.yml
This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.
> CI: pin GitHub Actions runners

- .github/workflows/elm_tests.yml
- bin/analyze-all-exercises-in-docker.sh
Closes #65 
This can't work in the CI until https://github.com/exercism/elm/pull/633 is merged, because it uses a script in there.
Edit: the PR is merged, and the script seems to work fine.
> Run analyzer on the elm repo in the CI

- src/Exercise/Bandwagoner.elm
- tests/Exercise/BandwagonerTest.elm
Closes #75 
[Sister PR here](https://github.com/exercism/website-copy/pull/2298).
As discussed in the issue, this is too early in the concept tree to require a pattern match/destructure.
> remove pattern matching rule from `bandwagoner`

- src/Exercise/AnnalynsInfiltration.elm
- src/ReviewConfig.elm
- tests/Exercise/AnnalynsInfiltrationTest.elm
Closes #19 
[Sister PR here](https://github.com/exercism/website-copy/pull/2299).
I don't this the rules would catch all strange solutions (like someone one `&&` along with an `if` condition or something), but it should catch obvious attempts.
> Add rule for concept exercise `annalyns-infiltration`

- src/Exercise/LuciansLusciousLasagna.elm
- src/ReviewConfig.elm
- tests/Exercise/LuciansLusciousLasagnaTest.elm
Closes #16 
[Sister PR here](https://github.com/exercism/website-copy/pull/2303).
Doesn't get simpler than this one.
The issue mentions "Verify that the whitespace adheres to community defaults" but that's not really doable, and not really fair in an environment without elm-format.
> Add rule for concept exercise `lucians-luscious-lasagna`

- src/Comment.elm
- tests/CommentTest.elm
I realized that in some cases, we could send duplicate comments, for example when relying on external rules.
I'm not sure what the Exercism interface does with duplicate comments, but better not send them in the first place.
> Remove duplicate comments

- .gitignore
- bin/check_files.sh
- bin/run.sh
- bin/smoke_test.sh
- src/ElmSyntaxHelpers.elm
- src/ReviewConfig.elm
- src/RuleConfig.elm
- src/Tags.elm
- test_data/strain/imperfect_solution/expected_tags.json
- test_data/strain/perfect_solution/expected_tags.json
- test_data/two-fer/imperfect_solution/expected_tags.json
- test_data/two-fer/perfect_solution/expected_tags.json
- tests/ElmSyntaxHelpersTest.elm
- tests/TagsTest.elm
Dear @mpizenberg, @ceddlyburge  and @ErikSchierboom,
Following our (fun and productive) discussion about tags, I came up with a prototype for the tagging mechanism, using elm-review's data extractors, which seems like a perfect fit, I have been able to add some tags very quickly.
Some comments:
- All of the tagging logic is in `src/Tags.elm`. If you are not familiar with elm-review, you can ignore the boilerplate, the core function is `matchExpression` and is easy to understand.
- For now, I have added random tags, some because they were easy, and because they were a bit more subtle (`LetExpression`, multiline strings). 
- There is one rule `commonTagsRule` that always returns the same tags `commonTags` for any project.
- For more complex traversals, for things like recursion, I would …
> Proposal for tagging mechanism

- src/Exercise/Sieve.elm
- src/ReviewConfig.elm
- tests/Exercise/SieveTest.elm
[Sister PR over here](https://github.com/exercism/website-copy/pull/2329).
The rule is pretty simple, there are two division in Elm (integer, float) and two modulo functions, disallow them all.
It's also worth doing, seeing how the example of "wrong" solutions are like 3x smaller than the official one.
@exercism/maintainers-admin I wonder if we are too late for @ErikSchierboom to approve this PR
> Add rule for practice exercise `sieve`
